version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.1
workflows:
  deploy:
    jobs:
      - aws-serverless/deploy:
          name: deploy-production
          stack-name: hackathon-lambda-1
          template: ./lambda.yaml
