version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.1
workflows:
  deploy:
    jobs:
      - aws-serverless/deploy:
          context: AWS
          name: deploy-production
          stack-name: hackathon-lambda-1
          template: ./template.yaml
          s3-bucket: travis-reed-hackisu-lambda-2-code
