version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.1
workflows:
  deploy:
    jobs:
      - build:
          context: AWS
          docker:
            - image: circleci/python
          steps:
            - run: aws s3 mb s3://travis-reed-hackisu-lambda-2-code
      - aws-serverless/deploy:
          context: AWS
          name: deploy-production
          stack-name: hackathon-lambda-1
          template: ./template.yaml
          s3-bucket: travis-reed-hackisu-lambda-2-code
