version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
#  aws-serverless: circleci/aws-serverless@1.0.1
jobs:
  aws-cli-create-bucket:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws s3 mb s3://travis-reed-hackisu-lambda-2-code
workflows:
  deploy:
    jobs:
      - aws-cli-create-bucket:
          context: AWS
#      - aws-serverless/deploy:
#          context: AWS
#          name: deploy-production
#          stack-name: hackathon-lambda-1
#          template: ./template.yaml
#          s3-bucket: travis-reed-hackisu-lambda-2-code
